type PizzaCategory = 'Meat' | 'Vegetarian' | 'Sea products' | 'Mushroom';
type PizzaSize = 22 | 28 | 33;
interface Pizza {
  id: number;
  name: string;
  category: PizzaCategory;
  description: string;
  sizes: PizzaSize[];
  // Используем Record для маппинга размера к цене
  prices: Record<PizzaSize, number>;
  imageUrl: string;
  isPopular: boolean;
}

export const pizzas: Pizza[] = [
  {
    id: 1,
    name: 'Venecia Meat',
    category: 'Meat',
    description: 'Filling: onion, beef, tomato, cheese, olives, pepperoni',
    sizes: [22, 28, 33],
    prices: { 22: 3200, 28: 4500, 33: 5800 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 2,
    name: 'Italian Vegetarian',
    category: 'Vegetarian',
    description: 'Filling: onion, potato, tomato, bell pepper, cheese, olives',
    sizes: [22, 28, 33],
    prices: { 22: 2800, 28: 3900, 33: 4900 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 3,
    name: 'Oceanic Venecia',
    category: 'Sea products',
    description: 'Filling: shrimps, mussels, tomato, cheese, olives, lemon zest',
    sizes: [22, 28, 33],
    prices: { 22: 4200, 28: 5600, 33: 7200 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 4,
    name: 'Forest Italian',
    category: 'Mushroom',
    description: 'Filling: mushrooms, onion, potato, cheese, white sauce',
    sizes: [22, 28, 33],
    prices: { 22: 3000, 28: 4200, 33: 5400 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 5,
    name: 'BBQ Venecia',
    category: 'Meat',
    description: 'Filling: chicken, bacon, onion, BBQ sauce, cheese, tomato',
    sizes: [22, 28, 33],
    prices: { 22: 3500, 28: 4800, 33: 6100 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 6,
    name: 'Garden Italian',
    category: 'Vegetarian',
    description: 'Filling: broccoli, corn, tomato, cheese, spinach, olives',
    sizes: [22, 28, 33],
    prices: { 22: 2700, 28: 3700, 33: 4700 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 7,
    name: 'Salmon Venecia',
    category: 'Sea products',
    description: 'Filling: salmon, cream cheese, tomato, olives, capers',
    sizes: [22, 28, 33],
    prices: { 22: 4500, 28: 5900, 33: 7500 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 8,
    name: 'Truffle Italian',
    category: 'Mushroom',
    description: 'Filling: wild mushrooms, truffle oil, cheese, onion, thyme',
    sizes: [22, 28, 33],
    prices: { 22: 3800, 28: 5200, 33: 6500 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 9,
    name: 'Pepperoni Venecia',
    category: 'Meat',
    description: 'Filling: pepperoni, extra cheese, tomato, oregano',
    sizes: [22, 28, 33],
    prices: { 22: 3100, 28: 4400, 33: 5700 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 10,
    name: 'Cheese Italian',
    category: 'Vegetarian',
    description: 'Filling: mozzarella, cheddar, parmesan, blue cheese, tomato',
    sizes: [22, 28, 33],
    prices: { 22: 3300, 28: 4600, 33: 5900 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 11,
    name: 'Shrimp Venecia',
    category: 'Sea products',
    description: 'Filling: garlic shrimps, tomato, cheese, olives, parsley',
    sizes: [22, 28, 33],
    prices: { 22: 4100, 28: 5400, 33: 6900 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 12,
    name: 'Champignon Italian',
    category: 'Mushroom',
    description: 'Filling: champignons, onion, tomato, cheese, olives, garlic',
    sizes: [22, 28, 33],
    prices: { 22: 2900, 28: 4100, 33: 5300 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 13,
    name: 'Meat Feast Venecia',
    category: 'Meat',
    description: 'Filling: ham, beef, chicken, bacon, cheese, tomato',
    sizes: [22, 28, 33],
    prices: { 22: 3800, 28: 5100, 33: 6600 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 14,
    name: 'Greek Italian',
    category: 'Vegetarian',
    description: 'Filling: feta, olives, cucumber, tomato, onion, oregano',
    sizes: [22, 28, 33],
    prices: { 22: 2900, 28: 4000, 33: 5100 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 15,
    name: 'Calamari Venecia',
    category: 'Sea products',
    description: 'Filling: calamari, garlic, cheese, tomato, bell pepper',
    sizes: [22, 28, 33],
    prices: { 22: 4000, 28: 5300, 33: 6800 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 16,
    name: 'Chanterelle Italian',
    category: 'Mushroom',
    description: 'Filling: chanterelles, onion, potato, cheese, dill',
    sizes: [22, 28, 33],
    prices: { 22: 3400, 28: 4700, 33: 6000 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 17,
    name: 'Salami Venecia',
    category: 'Meat',
    description: 'Filling: salami, cheese, tomato, olives, green pepper',
    sizes: [22, 28, 33],
    prices: { 22: 3200, 28: 4500, 33: 5800 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
  {
    id: 18,
    name: 'Spicy Italian',
    category: 'Vegetarian',
    description: 'Filling: jalapeno, corn, tomato, bell pepper, cheese, onion',
    sizes: [22, 28, 33],
    prices: { 22: 2800, 28: 3900, 33: 5000 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 19,
    name: 'Mixed Sea Venecia',
    category: 'Sea products',
    description: 'Filling: seafood mix, tomato, cheese, olives, basil',
    sizes: [22, 28, 33],
    prices: { 22: 4300, 28: 5700, 33: 7300 },
    imageUrl: '/pizzaExample.png',
    isPopular: true,
  },
  {
    id: 20,
    name: 'Shiitake Italian',
    category: 'Mushroom',
    description: 'Filling: shiitake mushrooms, sesame, cheese, green onion',
    sizes: [22, 28, 33],
    prices: { 22: 3600, 28: 4900, 33: 6200 },
    imageUrl: '/pizzaExample.png',
    isPopular: false,
  },
];
